org: jeanphilippelemieux66
app: content-hero-api
service: content-hero-rest-api

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dotenv:
    basePath: config/

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  stage: ${env:STAGE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${env:CONTENT_DYNAMODB_TABLE}'
        - Fn::Join:
            - '/'
            - - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${env:CONTENT_DYNAMODB_TABLE}'
              - 'index/*'
  environment:
    AUTH0_CLIENT_PUBLIC_KEY: ${file(${env:AUTH0_CLIENT_PUBLIC_KEY_PATH})}

functions:
  # Content API
  content-create:
    handler: api/content/create.handler
    events:
      - http:
          path: content
          method: post
          cors: true

  content-list:
    handler: api/content/list.handler
    events:
      - http:
          path: content
          method: get
          cors: true

  content-get:
    handler: api/content/get.handler
    events:
      - http:
          path: content/{id}
          method: get
          cors: true

  content-update:
    handler: api/content/update.handler
    events:
      - http:
          path: content/{id}
          method: put
          cors: true

  content-delete:
    handler: api/content/delete.handler
    events:
      - http:
          path: content/{id}
          method: delete
          cors: true

resources:
  Resources:
    ContentDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userEmail
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${env:CONTENT_DYNAMODB_TABLE}
        GlobalSecondaryIndexes:
          - IndexName: userEmailIndex
            KeySchema:
              - AttributeName: userEmail
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
