# org: jeanphilippelemieux66
# app: content-hero-api

service: content-hero-rest-api

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dotenv:
    basePath: config/

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AUTH0_CLIENT_PUBLIC_KEY: ${file(${env:AUTH0_CLIENT_PUBLIC_KEY_PATH})}

functions:
  # Content API
  content-create:
    handler: api/content/create.handler
    events:
      - http:
          path: content
          method: post
          cors: true

  content-list:
    handler: api/content/list.handler
    events:
      - http:
          path: content
          method: get
          cors: true

  content-get:
    handler: api/content/get.handler
    events:
      - http:
          path: content/{id}
          method: get
          cors: true

  content-update:
    handler: api/content/update.handler
    events:
      - http:
          path: content/{id}
          method: put
          cors: true

  content-delete-all:
    handler: api/content/delete-all.handler
    events:
      - http:
          path: content/all
          method: delete
          cors: true

  content-delete:
    handler: api/content/delete.handler
    events:
      - http:
          path: content/{id}
          method: delete
          cors: true
